// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunnersAppBackEndApi.Data;

#nullable disable

namespace RunnersAppBackEndApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260305165001_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RunnersAppBackEndApi.Models.Entities.Activity", b =>
                {
                    b.Property<int>("activityid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activityid"));

                    b.Property<string>("activity_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("eventid")
                        .HasColumnType("int");

                    b.Property<int>("profileid")
                        .HasColumnType("int");

                    b.HasKey("activityid");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("RunnersAppBackEndApi.Models.Entities.Event", b =>
                {
                    b.Property<int>("eventid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eventid"));

                    b.Property<DateTime>("event_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("event_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("event_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("event_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("eventid");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RunnersAppBackEndApi.Models.Entities.Performance", b =>
                {
                    b.Property<int>("performannceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("performannceid"));

                    b.Property<string>("vo2max")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("performannceid");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("RunnersAppBackEndApi.Models.Entities.Profile", b =>
                {
                    b.Property<int>("profileid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("profileid"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("performannceid")
                        .HasColumnType("int");

                    b.Property<int>("phone")
                        .HasColumnType("int");

                    b.Property<string>("profileimage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("profileid");

                    b.ToTable("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
